### PR TITLE
fringe: Update fringe page for 2018

### PR DESCRIPTION
**Pull request by purpleidea**
I'm just assuming for Puppet, Chef and Foreman, but mgmtconfig would
like to come back, so I figured I'd update this for everyone.
Uninterested users should send a patch after this is merged, or ping so
that I fix this before merging.

### CODE REVIEW

**Comment by purpleidea** [comment]
Maybe @thatch45 and @cachedout are interested too (salt)

**Comment by KrisBuytaert** [comment]
Yeah that's a lot of assumptions in one ..PR . some folks need to chime in :) 

cc: @ahpook  @robynbergeron @GregSutcliffe  ...

**Comment by GregSutcliffe** [comment]
We're definitely in for a hackday, thanks for the legwork @purpleidea :)

**Comment by mirako** [comment]
Puppet will host a hack day on the 8th. Thanks @purpleidea.

**Comment by purpleidea** [comment]
So @nathenharvey sent me some patches by email (cool, right, I hadn't used `git am` in years) but it works great, and they all applied.

So I think this is ready to merge, and anyone that wants further changes can open a new PR i guess?

**Comment by purpleidea** [comment]
@mirako I assume you mean the 7th?

**Comment by nathenharvey** [comment]
I'm :+1: on getting this merged!

**Pull request merged**
